"""add unique constraint for wam_id

Revision ID: 2116283378df
Revises: b4574a532599
Create Date: 2026-02-23 10:36:15.055800

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2116283378df"
down_revision: Union[str, Sequence[str], None] = "b4574a532599"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("archive_records", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_archive_records_wam_id", ["wam_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("archive_records", schema=None) as batch_op:
        batch_op.drop_constraint("uq_archive_records_wam_id", type_="unique")

    # ### end Alembic commands ###
