"""create archive_records table

Revision ID: b4574a532599
Revises:
Create Date: 2026-02-04 13:33:12.876590

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b4574a532599"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archive_records",
        sa.Column("profile_name", sa.Text(), nullable=False),
        sa.Column("record_url", sa.Text(), nullable=False),
        sa.Column("archive_link", sa.Text(), nullable=False),
        sa.Column("domain_type", sa.String(length=100), nullable=False),
        sa.Column("first_capture_display", sa.String(length=100), nullable=False),
        sa.Column("latest_capture_display", sa.String(length=100), nullable=False),
        sa.Column("ongoing", sa.Boolean(), nullable=False),
        sa.Column("wam_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("sort_name", sa.Text(), nullable=False),
        sa.Column("first_character", sa.String(length=3), nullable=False),
        sa.Column("record_hash", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("archive_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_archive_records_first_character"),
            ["first_character"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_archive_records_record_hash"), ["record_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_archive_records_sort_name"), ["sort_name"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("archive_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_archive_records_sort_name"))
        batch_op.drop_index(batch_op.f("ix_archive_records_record_hash"))
        batch_op.drop_index(batch_op.f("ix_archive_records_first_character"))

    op.drop_table("archive_records")
    # ### end Alembic commands ###
